StudyPlanner/WebApp/Areas/Admin/Controllers/SubjectController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using App.DAL.EF;
using App.Domain.DbEntities;
using App.Domain.ManyToMany;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace WebApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SubjectController : Controller
    {
        private readonly AppDbContext _context;

        public SubjectController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Subject
        public async Task<IActionResult> Index()
        {
            var appDbContext = _context.Subjects.Include(s => s.Module);
            return View(await appDbContext.ToListAsync());
        }

        // GET: Subject/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var subject = await _context.Subjects
                .Include(s => s.Module)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (subject == null)
            {
                return NotFound();
            }

            return View(subject);
        }

        // GET: Subject/Create
        public IActionResult Create()
        {
            ViewData["ModuleId"] = new SelectList(_context.Modules, "Id", "Label");
            return View();
        }

        // POST: Subject/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Label,Description,EAP,ModuleId,Id,CreatedBy,CreatedAt,UpdatedBy,UpdatedAt")] Subject subject)
        {
            if (ModelState.IsValid)
            {
                subject.Id = Guid.NewGuid();
                _context.Add(subject);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ModuleId"] = new SelectList(_context.Modules, "Id", "Label", subject.ModuleId);
            return View(subject);
        }

        // GET: Subject/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var subject = await _context.Subjects.FindAsync(id);
            if (subject == null)
            {
                return NotFound();
            }
            ViewData["ModuleId"] = new SelectList(_context.Modules, "Id", "Label", subject.ModuleId);
            return View(subject);
        }

        // POST: Subject/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Label,Description,EAP,ModuleId,Id,CreatedBy,CreatedAt,UpdatedBy,UpdatedAt")] Subject subject)
        {
            if (id != subject.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(subject);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SubjectExists(subject.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ModuleId"] = new SelectList(_context.Modules, "Id", "Label", subject.ModuleId);
            return View(subject);
        }

        // GET: Subject/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var subject = await _context.Subjects
                .Include(s => s.Module)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (subject == null)
            {
                return NotFound();
            }

            return View(subject);
        }

        // POST: Subject/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var subject = await _context.Subjects.FindAsync(id);
            if (subject != null)
            {
                _context.Subjects.Remove(subject);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SubjectExists(Guid id)
        {
            return _context.Subjects.Any(e => e.Id == id);
        }
    }
}

StudyPlanner/WebApp/Areas/Public/Controllers/SubjectsController.cs
using App.BLL.DTO.ManyToMany;
using App.Contracts.BLL;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using App.BLL.DTO.Entities;
using App.BLL.DTO.Identity;
using App.Domain;
using Microsoft.AspNetCore.Authorization;
using User = App.Domain.Identity.User;
using Microsoft.AspNetCore.Identity;
using WebApp.Areas.Public.ViewModels;

namespace WebApp.Areas.Public.Controllers
{
    [Area("Public")]
    [Authorize]
    public class SubjectsController : Controller
    {
        private readonly IAppBLL _bll;
        private readonly UserManager<User> _userManager;

        public SubjectsController(IAppBLL bll, UserManager<User> userManager)
        {
            _bll = bll;
            _userManager = userManager;
        }

        // GET: Subjects
        public async Task<IActionResult> Index(Guid? subjectId)
        {
            var userId = Guid.Parse(_userManager.GetUserId(User)!);
            var vm = new SubjectsIndexViewModel
            {
                Subjects = await _bll.Subjects.GetAllChosenSortedAsync(userId),
                WorkTaskRoles = await _bll.WorkTaskRoles.GetAllAsync(userId),
                UserId = userId,
                SubjectId = subjectId
            };
            if (subjectId != null)
            {
                vm.SubjectAccessTypes = (await _bll.SubjectRoles.GetAllOfSubjectAsync((Guid)subjectId, userId))
                    .Select(w => w.AccessType).ToList();
                vm.ChosenWorkTasks = await _bll.WorkTasks.GetAllChosenSortedOfSubjectAsync(userId, subjectId.Value);
                vm.PublicWorkTasks = await _bll.WorkTasks.GetAllPublicSortedOfSubjectAsync(userId, subjectId.Value);
                vm.Subject = vm.Subjects.FirstOrDefault(s => s.Id.Equals(subjectId.Value));
            }
            else
            {
                vm.ChosenWorkTasks = await _bll.WorkTasks.GetAllChosenSortedAsync(userId);
                vm.PublicWorkTasks = await _bll.WorkTasks.GetAllPublicSortedAsync(userId);
                
            }
            
            return View(vm);
        }

        // GET: Subjects/Details/5
        public async Task<IActionResult> SubjectDetails(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var userId = Guid.Parse(_userManager.GetUserId(User)!);
            var vm = new SubjectsSubjectDetailsDeleteViewModel()
            {
                Subject = await _bll.Subjects.FirstOrDefaultAsync(id.Value, userId),
                UserSubjects = (await _bll.UserSubjects.GetAllOfSubjectAsync(id.Value, userId)).ToList(),
                SubjectRoles = (await _bll.SubjectRoles.GetAllOfSubjectAsync(id.Value, userId)).ToList()
            };
            if (vm.Subject == null)
            {
                return NotFound();
            }

            return View(vm);
        }
        // GET: WorkTasks/Details/5
        public async Task<IActionResult> WorkTaskDetails(Guid? id, Guid? subjectId)
        {
            if (id == null)
            {
                return NotFound();
            }
            var userId = Guid.Parse(_userManager.GetUserId(User)!);
            var vm = new SubjectsTaskDetailsDeleteViewModel()
            {
                WorkTask = await _bll.WorkTasks.FirstOrDefaultAsync(id.Value, userId),
                UserWorkTasks = (await _bll.UserWorkTasks.GetAllOfWorkTaskAsync(id.Value, userId)).ToList(),
                WorkTaskRoles = (await _bll.WorkTaskRoles.GetAllOfWorkTaskAsync(id.Value, userId)).ToList(),
                SubjectId = subjectId
                
            };
            
            if (vm.WorkTask == null)
            {
                return NotFound();
            }

            return View(vm);
        }

        // GET: Subjects/CreateWorkTask
        public async Task<IActionResult> CreateWorkTask(Guid subjectId)
        {
            var userId = Guid.Parse(_userManager.GetUserId(User)!);
            var vm = new SubjectsCreateEditTaskViewModel()
            {
                WorkTask = new WorkTask()
                {
                    SubjectId = subjectId
                },
                ParentWorkTaskSelectList = new SelectList(await _bll.WorkTasks.GetAllAsync(userId), nameof(WorkTask.Id),
                    nameof(WorkTask.Label)),
                WorkTaskCodeSelectList = new SelectList(await _bll.WorkTasks.GetAllAsync(userId), nameof(WorkTask.Id),
                    nameof(WorkTask.Code)),
                RoleSelectList = new MultiSelectList(await _bll.Roles.GetAllAsync(userId), nameof(Role.Id),
                    nameof(Role.Name))
            };


            return View(vm);
        }

        // POST: Subjects/CreateWorkTask
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateWorkTask(SubjectsCreateEditTaskViewModel vm)
        {
            var userId = Guid.Parse(_userManager.GetUserId(User)!);
            ModelState.ClearValidationState("Roles");
            ModelState.MarkFieldValid("Roles");
            if (ModelState.IsValid)
            {
                vm.WorkTask.Id = Guid.NewGuid();
                vm.WorkTask.CreatedBy = userId;
                vm.WorkTask.CreatedAt = DateTime.Now;
                _bll.WorkTasks.Add(vm.WorkTask);
                await _bll.SaveChangesAsync();
                foreach (var role in vm.Roles ?? [])
                {
                    _bll.WorkTaskRoles.Add(new WorkTaskRole()
                    {
                        Id = Guid.NewGuid(),
                        AccessType = vm.AccessType,
                        RoleId = role,
                        WorkTaskId = vm.WorkTask.Id
                    });
                }
                
                _bll.UserWorkTasks.Add(new UserWorkTask()
                {
                    Id = Guid.NewGuid(),
                    Status = EStatus.Claimed,
                    UserId = userId,
                    WorkTaskId = vm.WorkTask.Id
                });
                await _bll.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new {subjectId = vm.WorkTask.SubjectId});
            }
            
            
            vm.ParentWorkTaskSelectList = new SelectList(await _bll.WorkTasks.GetAllAsync(userId), nameof(WorkTask.Id),
                nameof(WorkTask.Label), vm.WorkTask.ParentWorkTaskId);
            vm.RoleSelectList = new MultiSelectList(await _bll.Roles.GetAllAsync(userId),
                nameof(Role.Id), nameof(Role.Name), vm.Roles.ToArray());
            return View(vm);
        }
        
        
        // GET: Subjects/Create
        public async Task<IActionResult> CreateSubject()
        {
            var userId = Guid.Parse(_userManager.GetUserId(User)!);
            var vm = new SubjectsCreateEditSubjectViewModel()
            {
                ModuleSelectList = new SelectList(await _bll.Modules.GetAllAsync(userId), nameof(Module.Id),
                    nameof(Module.Label)),
                RoleSelectList = new SelectList(await _bll.Roles.GetAllAsync(userId), nameof(Role.Id),
                    nameof(Role.Name))
            };


            return View(vm);
        }

        // POST: Subjects/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateSubject(SubjectsCreateEditSubjectViewModel vm)
        {
            var userId = Guid.Parse(_userManager.GetUserId(User)!);
            ModelState.ClearValidationState("Roles");
            ModelState.MarkFieldValid("Roles");
            if (ModelState.IsValid)
            {
                vm.Subject.Id = Guid.NewGuid();
                vm.Subject.CreatedBy = userId;
                vm.Subject.CreatedAt = DateTime.Now;
                _bll.Subjects.Add(vm.Subject);
                await _bll.SaveChangesAsync();
                foreach (var role in vm.Roles ?? [])
                {
                    _bll.SubjectRoles.Add(new SubjectRole()
                    {
                        Id = Guid.NewGuid(),
                        AccessType = vm.AccessType,
                        RoleId = role,
                        SubjectId = vm.Subject.Id
                    });
                }
                
                _bll.UserSubjects.Add(new UserSubject()
                {
                    Id = Guid.NewGuid(),
                    UserId = userId,
                    Status = EStatus.Claimed,
                    Semester = vm.Semester,
                    SubjectId = vm.Subject.Id
                });
                await _bll.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            
            vm.ModuleSelectList = new SelectList(await _bll.Modules.GetAllAsync(userId), nameof(Module.Id), nameof(Module.Label), vm.Subject.ModuleId);
            vm.RoleSelectList = new SelectList(await _bll.Roles.GetAllAsync(userId), nameof(Role.Id), nameof(Role.Name), vm.Roles);
            return View(vm);
        }
        
        // GET: Subjects/Edit/5
        public async Task<IActionResult> EditWorkTask(Guid? id, Guid? subjectId)
        {
            if (id == null)
            {
                return NotFound();
            }
            var userId = Guid.Parse(_userManager.GetUserId(User)!);
            var workTask = await _bll.WorkTasks.FirstOrDefaultAsync(id.Value, userId);
            if (workTask == null)
            {
                return NotFound();
            }

StudyPlanner/WebApp/Areas/Public/Views/Subjects/CreateSubject.cshtml
@using App.Domain
@model WebApp.Areas.Public.ViewModels.SubjectsCreateEditSubjectViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Subject</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateSubject">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Subject.Label" class="control-label"></label>
                <input asp-for="Subject.Label" class="form-control" />
                <span asp-validation-for="Subject.Label" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Subject.Description" class="control-label"></label>
                <input asp-for="Subject.Description" class="form-control" />
                <span asp-validation-for="Subject.Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Subject.EAP" class="control-label"></label>
                <input asp-for="Subject.EAP" class="form-control" />
                <span asp-validation-for="Subject.EAP" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Subject.ModuleId" class="control-label">Module</label>
                <select asp-for="Subject.ModuleId" class="form-control" asp-items="@Model.ModuleSelectList">
                    <option></option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="Semester" class="control-label"></label>
                <input asp-for="Semester" class="form-control" />
                <span asp-validation-for="Semester" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Roles" class="control-label">Share</label>
                <select asp-for="Roles" class="form-control" asp-items="@Model.RoleSelectList">
                    <option></option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="AccessType" class="control-label">Rights</label>
                <select asp-for="AccessType" class ="form-control" asp-items="@Html.GetEnumSelectList<EAccessType>()"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

StudyPlanner/WebApp/Areas/Public/Views/Subjects/CreateWorkTask.cshtml
@using App.Domain
@model WebApp.Areas.Public.ViewModels.SubjectsCreateEditTaskViewModel

@{
ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Task</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateWorkTask">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="WorkTask.Label" class="control-label"></label>
                <input asp-for="WorkTask.Label" class="form-control" />
                <span asp-validation-for="WorkTask.Label" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WorkTask.Deadline" class="control-label"></label>
                <input asp-for="WorkTask.Deadline" class="form-control" />
                <span asp-validation-for="WorkTask.Deadline" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WorkTask.TimeExpectancy" class="control-label">Time Expectancy (d.h:m:s)</label>
                <input asp-for="WorkTask.TimeExpectancy" class="form-control" />
                <span asp-validation-for="WorkTask.TimeExpectancy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WorkTask.Code" class="control-label">Code</label>
                <select asp-for="WorkTask.Code" class="form-control" asp-items="@Model.WorkTaskCodeSelectList">
                    <option></option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="WorkTask.ParentWorkTaskId" class="control-label">Parent Task</label>
                <select asp-for="WorkTask.ParentWorkTaskId" class="form-control" asp-items="@Model.ParentWorkTaskSelectList">
                    <option></option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="WorkTask.Field" class="control-label">Field</label>
                <select asp-for="WorkTask.Field" class ="form-control" asp-items="@Html.GetEnumSelectList<EField>()"></select>
            </div>
            <div class="form-group">
                <label asp-for="WorkTask.TaskType" class="control-label">Task Type</label>
                <select asp-for="WorkTask.TaskType" class ="form-control" asp-items="@Html.GetEnumSelectList<ETaskType>()"></select>
            </div>
            <div class="form-group">
                <label asp-for="Roles" class="control-label">Share</label>
                <select asp-for="Roles" class="form-control" asp-items="@Model.RoleSelectList">
                    <option></option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="AccessType" class="control-label">Rights</label>
                <select asp-for="AccessType" class="form-control" asp-items="@Html.GetEnumSelectList<EAccessType>()"></select>
            </div>
            <input type="hidden" asp-for="WorkTask.SubjectId" />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-route-subjectId="@Model.WorkTask.SubjectId">Back to List</a>
</div>

@section Scripts {
@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

StudyPlanner/WebApp/Areas/Public/Views/Subjects/Index.cshtml
@using App.Domain
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model WebApp.Areas.Public.ViewModels.SubjectsIndexViewModel

@{
    ViewData["Title"] = "Index";
    List<EAccessType> roles;
}


@if (Model.Subject != null)
{
    <h1>@(Model.Subject.Label)</h1>

    if (Model.Subject.CreatedBy == Model.UserId || Model.SubjectAccessTypes.Contains(EAccessType.Admin) || Model.SubjectAccessTypes.Contains(EAccessType.Edit))
    {
        <div>
            <a asp-action="SubjectDetails" asp-route-id="@Model.SubjectId">Details</a> |
            <a asp-action="EditSubject" asp-route-id="@Model.SubjectId">Edit</a> |
            <a asp-action="DeleteSubject" asp-route-id="@Model.SubjectId">Delete</a>
        </div>
    }
    else
    {
        <div>
            <a asp-action="SubjectDetails" asp-route-id="@Model.SubjectId">Details</a>
        </div>
    }
    
    <p>
        <a asp-action="CreateWorkTask" asp-route-subjectId="@Model.Subject.Id">Create New Task</a>
    </p>
}
else
{
    <h1>Subjects</h1>

    <p>
        <a asp-action="CreateSubject">Create New Subject</a>
    </p>
}

<h3>
    <p>
        <a class="text-dark" asp-area="Public" asp-controller="Subjects" asp-action="Index">All</a>
    
    @foreach (var item in Model.Subjects)
    {
        @(" | ")
        <a class="text-dark" asp-area="Public" asp-controller="Subjects" asp-route-subjectId="@item.Id" asp-action="Index">@item.Label</a>
    }
    </p>
</h3>

@if (Model.Subject != null)
{
    <h3>Description</h3>
    <div>
        @Model.Subject?.Description
    </div>
}

<table class="table">
    <tr>
        <td>
            <h4>Public</h4>
            <table class="table">
                <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.WorkTask.Label)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.WorkTask.Deadline)
                    </th>
                    <th>
                        Time Expectancy
                    </th>
                    <th>
                        Task Type
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.WorkTask.Field)
                    </th>
                    <th>
                        Parent Task
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.WorkTask.Subject)
                    </th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                @foreach (var item in Model.PublicWorkTasks)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Label)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Deadline)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TimeExpectancy)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TaskType)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Field)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ParentWorkTask!.Label)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Subject!.Label)
                        </td>

                        @{
                            roles = Model.WorkTaskRoles.Where(w => w.WorkTaskId == item.Id).Select(w => w.AccessType).ToList();
                        }

                        @if (item.CreatedBy == Model.UserId || roles.Contains(EAccessType.Admin) || roles.Contains(EAccessType.Edit))
                        {
                            <td>
                                <a asp-action="WorkTaskDetails" asp-route-id="@item.Id" asp-route-subjectId="@Model.SubjectId">Details</a> |
                                <a asp-action="EditWorkTask" asp-route-id="@item.Id" asp-route-subjectId="@Model.SubjectId">Edit</a> |
                                <a asp-action="DeleteWorkTask" asp-route-id="@item.Id" asp-route-subjectId="@Model.SubjectId">Delete</a> |
                                <a asp-action="Add" asp-route-id="@item.Id" asp-route-subjectId="@Model.SubjectId">Add</a>
                            </td>
                        }
                        else
                        {
                            <td>
                                <a asp-action="WorkTaskDetails" asp-route-id="@item.Id" asp-route-subjectId="@Model.SubjectId">Details</a> |
                                <a asp-action="Add" asp-route-id="@item.Id" asp-route-subjectId="@Model.SubjectId">Add</a>
                            </td>
                        }
                    </tr>
                }
                </tbody>
            </table>
        </td>
        <td></td>
        <td>
            <h4>Selected</h4>
            <table class="table">
                <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.WorkTask.Label)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.WorkTask.Deadline)
                    </th>
                    <th>
                        Time Expectancy
                    </th>
                    <th>
                        Task Type
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.WorkTask.Field)
                    </th>
                    <th>
                        Parent Task
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.WorkTask.Subject)
                    </th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                @foreach (var item in Model.ChosenWorkTasks)
                {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Label)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Deadline)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TimeExpectancy)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TaskType)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Field)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ParentWorkTask!.Label)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Subject!.Label)
                    </td>

                    @{
                    roles = Model.WorkTaskRoles.Where(w => w.WorkTaskId == item.Id).Select(w => w.AccessType).ToList();
                    }

                    @if( item.CreatedBy == Model.UserId || roles.Contains(EAccessType.Admin) || roles.Contains(EAccessType.Edit))
                    {
                    <td>
                        <a asp-action="WorkTaskDetails" asp-route-id="@item.Id" asp-route-subjectId="@Model.SubjectId">Details</a> |
                        <a asp-action="EditWorkTask" asp-route-id="@item.Id" asp-route-subjectId="@Model.SubjectId">Edit</a> |
                        <a asp-action="DeleteWorkTask" asp-route-id="@item.Id" asp-route-subjectId="@Model.SubjectId">Delete</a>
                        <a asp-action="Remove" asp-route-id="@item.Id" asp-route-subjectId="@Model.SubjectId">Remove</a>
                    </td>
                    }
                    else
                    {
                    <td>
                        <a asp-action="WorkTaskDetails" asp-route-id="@item.Id" asp-route-subjectId="@Model.SubjectId">Details</a>
                        <a asp-action="Remove" asp-route-id="@item.Id" asp-route-subjectId="@Model.SubjectId">Remove</a>
                    </td>
                    }
                </tr>
                }
                </tbody>
            </table>
        </td>
    </tr>
</table>